#!/bin/sh -eux

which defaults || {
	echo 'must run on a mac, /usr/bin/defaults not in your $PATH'
	exit 1
}

# menu bar: opaque
defaults write NSGlobalDomain AppleEnableMenuBarTransparency -bool false

# dock: pin in corner
defaults write com.apple.dock pinning -string start

# dock: make icons of hidden applications translucent
defaults write com.apple.dock showhidden -bool true

killall Dock


# Enable full keyboard access for all controls
# (e.g. enable Tab in modal dialogs)
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3


## hardware

# wait 24hrs before moving sleep-storage from ram to disk
sudo pmset -a standbydelay 86400

# Disable local Time Machine backups
sudo tmutil disablelocal


# see also
# https://github.com/mathiasbynens/dotfiles/blob/master/.osx
# http://osxdaily.com/2013/01/21/mac-slow-wake-from-sleep-fix/
